export const ROUTES = {
  LOGIN: '/login',
  ACCESS_DENIED: '/access-denied',
  DASHBOARD: '/dashboard',
  COORDINATORS: '/coordinators',
  COORDINATORS_NEW: '/coordinators/new',
  COORDINATOR_DETAIL: (id: string) => `/coordinators/${id}`,
  COORDINATOR_EDIT: (id: string) => `/coordinators/${id}/edit`,
  VOTERS: '/voters',
  VOTERS_NEW: '/voters/new',
  VOTER_DETAIL: (id: string) => `/voters/${id}`,
  VOTER_EDIT: (id: string) => `/voters/${id}/edit`,
  POLLING_PLACES: '/polling-places',
  POLLING_PLACES_NEW: '/polling-places/new',
  POLLING_PLACE_DETAIL: (id: string) => `/polling-places/${id}`,
  POLLING_PLACE_EDIT: (id: string) => `/polling-places/${id}/edit`,
  REPORTS: '/reports',
  SETTINGS: '/settings',
} as const
